language: php

services:
  - mysql

jobs:
  fast_finish: true
  include:
    - env: DBTYPE=mysql; MW=1.31.3
      php: 7.1
    - env: DBTYPE=sqlite; MW=1.33.2
      php: 7.2
    - env: DBTYPE=mysql; MW=1.34.0
      php: 7.3
    - env: DBTYPE=mysql; MW=master
      php: 7.4

install:
  - travis_retry composer self-update
  - bash .travis.install.sh

script:
  - ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/Network/phpunit.xml.dist
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]] ; then cd ../phase3/extensions/Network/ && make ci ; fi

after_success:
  - if [[ "$TYPE" != "coverage" ]]; then exit 0; fi
  - ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/Network/phpunit.xml.dist --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
