name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: "PHPUnit: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"

    strategy:
      matrix:
        include:
          - mw: 'REL1_33'
            php: 7.3
          - mw: 'REL1_34'
            php: 7.4
          - mw: 'master'
            php: 7.4

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mediawiki

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - name: Cache MediaWiki
        id: cache-mediawiki
        uses: actions/cache@v2
        with:
          path: |
            mediawiki
            !mediawiki/extensions/
            !mediawiki/vendor/
          key: mw_${{ matrix.mw }}-php${{ matrix.php }}-v20

      - name: Cache Composer cache
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: composer-php${{ matrix.php }}

      - name: Install MediaWiki
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        working-directory: ~
        run: curl https://gist.githubusercontent.com/JeroenDeDauw/49a3858653ff4b5be7ec849019ede06c/raw/installMediaWiki.sh | bash -s ${{ matrix.mw }} Network

      - uses: actions/checkout@v2
        with:
          path: mediawiki/extensions/Network

      - name: Composer update
        run: composer update

      - name: Run PHPUnit
        run: php tests/phpunit/phpunit.php -c extensions/Network/phpunit.xml.dist

  static-analysis:
    name: "Static Analysis"

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mediawiki/extensions/Network

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring
          tools: composer, cs2pr

      - uses: ProfessionalWiki/setup-mediawiki@0.1
        with:
          extension: Network

      - uses: actions/checkout@v2
        with:
          path: mediawiki/extensions/Network

      - name: Composer install
        run: composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader

      - name: PHPStan
        run: php vendor/bin/phpstan analyse --error-format=checkstyle --no-progress | cs2pr

      - name: Psalm
        run: php vendor/bin/psalm
